version: 2

sources: 
  - name: raw
    description: Transformed from gz_raw_data
    tables: 
      - name: product
        description: Transformed from raw_gz_product
      - name: sales
        description: Tranformed from raw_gz_sales
      - name: ship
        description: Tranformed from raw_gz_ship